// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7k-6Xm5Mp8x7q2-FgyaX73z-ghbn2YEY',
    appId: '1:855923272890:web:0debc859e6865f2d3ae683',
    messagingSenderId: '855923272890',
    projectId: 'traffic-monitoring-record',
    authDomain: 'traffic-monitoring-record.firebaseapp.com',
    storageBucket: 'traffic-monitoring-record.firebasestorage.app',
    measurementId: 'G-XYE1W50BDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkGO4BrJt_YxQCA6_hj1NA1sYIwwnVR4',
    appId: '1:855923272890:android:cef9e105295f96de3ae683',
    messagingSenderId: '855923272890',
    projectId: 'traffic-monitoring-record',
    storageBucket: 'traffic-monitoring-record.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0IRtJaKDdRUOBIChE1N2E0foXmxWiw6I',
    appId: '1:855923272890:ios:b1aa844c3ee0bab03ae683',
    messagingSenderId: '855923272890',
    projectId: 'traffic-monitoring-record',
    storageBucket: 'traffic-monitoring-record.firebasestorage.app',
    iosBundleId: 'com.example.trafficmonitoringrecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0IRtJaKDdRUOBIChE1N2E0foXmxWiw6I',
    appId: '1:855923272890:ios:b1aa844c3ee0bab03ae683',
    messagingSenderId: '855923272890',
    projectId: 'traffic-monitoring-record',
    storageBucket: 'traffic-monitoring-record.firebasestorage.app',
    iosBundleId: 'com.example.trafficmonitoringrecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7k-6Xm5Mp8x7q2-FgyaX73z-ghbn2YEY',
    appId: '1:855923272890:web:eb3c0ab018296bb73ae683',
    messagingSenderId: '855923272890',
    projectId: 'traffic-monitoring-record',
    authDomain: 'traffic-monitoring-record.firebaseapp.com',
    storageBucket: 'traffic-monitoring-record.firebasestorage.app',
    measurementId: 'G-LQNNHN781H',
  );
}
